/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./../theme/components/Comment.vue')['default']
    DemoWrap: typeof import('./../theme/components/DemoWrap.vue')['default']
    ListProjects: typeof import('./../theme/components/ListProjects.vue')['default']
    Loading: typeof import('./../theme/components/Loading.vue')['default']
    ToolItem: typeof import('./../theme/components/ToolItem.vue')['default']
    ToolWrap: typeof import('./../theme/components/ToolWrap.vue')['default']
  }
}
